### ISSUE TITLE
Message not always an array

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/sprint-helper-bot#9]
Getting repeated downtime with this error in the logs:

```sh
TypeError: message[0].slice is not a function
    at Client.<anonymous> (/root/ipfs-sprint-helper/index.js:18:36)
    at emitMany (events.js:108:13)
    at Client.emit (events.js:182:7)
    at Client.<anonymous> (/root/ipfs-sprint-helper/node_modules/irc/lib/irc.js:557:22)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at iterator (/root/ipfs-sprint-helper/node_modules/irc/lib/irc.js:846:26)
    at Array.forEach (native)
    at Socket.handleData (/root/ipfs-sprint-helper/node_modules/irc/lib/irc.js:841:15)
    at emitOne (events.js:77:13)

```

**Comment by RichardLitt** [comment]
Launched a debugging branch on the server. Will check the logs when I see them coming in.
